language: java
jdk:
  - oraclejdk8
sudo: false
script:
  - mvn clean verify package
deploy:
  provider: releases
  api_key:
    secure: "comming_soon"
  file: 'target/sampling-message-server-0.1-jar-with-dependencies.jar'
  skip_cleanup: true